// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoTCdos8RmFVNZcqOtsIrRPmYA4Nolfao',
    appId: '1:936138807124:android:1af193fa21a7626e831ac1',
    messagingSenderId: '936138807124',
    projectId: 'manifest-7377f',
    storageBucket: 'manifest-7377f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-fPuu6IYHTCvv6EJTj1vTzEX7HffdeQA',
    appId: '1:936138807124:ios:742df1223ca202c2831ac1',
    messagingSenderId: '936138807124',
    projectId: 'manifest-7377f',
    storageBucket: 'manifest-7377f.firebasestorage.app',
    androidClientId: '936138807124-dp39lqtju9jpsgnp4945bqsjjkfk0pka.apps.googleusercontent.com',
    iosClientId: '936138807124-8avdujc8shms6v82f8meplhssoodh068.apps.googleusercontent.com',
    iosBundleId: 'com.manifest.so',
  );

}